### ISSUE TITLE
我想使用没有androidX的sdk，请问ipc-sdk有没有不是androidX的可用版本

### ISSUE THREAD

**Issue by DalesDawson** [tuya/tuya-iotos-android-ipc-demo#5]
com.tuya.smart:tuyasmart:3.17.13 这个涂鸦home sdk我使用的是3.17.13，请问对应的com.tuya.smart:tuyasmart-ipc-sdk 应该是使用哪个版本呢？就是没有适配androidX的

**Comment by Innocencellh** [comment]
有历史版本，但是不推荐使用，已暂停维护了
